"""Grasp demonstrations for a learned policy, generated by the scripted pipeline.

Each episode: one object (can upright / can lying / apple / orange / peach) at a random
spot and heading on the right arm's side of the bin-conveyor table; the scripted Demo
(grasp library + planner + waypoints) plans, reaches, closes and proof-lifts it. The
REACH and GRASP phases are recorded at 10 Hz; an episode is kept only if the proof
lift passed (the object came up with the hand). Raw arrays are saved, one .npz per
episode, so the LeRobot conversion (scripts/to_lerobot.py) can choose its features:

    time, phase                      sim time (s), 0 = reach, 1 = grasp
    arm_q, arm_ctrl                  (T, 7)  measured / commanded arm joints
    hand_q, hand_ctrl                (T, nh) measured hand joints / hand actuator commands
    forces                           (T, 5)  normal force per finger (thumb..pinky)
    wrist, wrist_cmd                 (T, 4, 4) measured wrist pose / FK of the arm command
    object, object_est               (T, 4, 4) object pose now / as perceived at PERCEIVE
    kind, pose, xy, yaw              object key, rest pose, spot, heading

    python -m scripts.generate_grasp_demos --count 200 --seed 1 --out artifacts/demos
"""

from __future__ import annotations

import argparse
import time
from pathlib import Path

import numpy as np

from simulation.pick_place.bin_conveyor_task import BELT, BOX, BOX_HALF, BOX_WALL
from simulation.pick_place.bin_task import PLATFORM
from simulation.pick_place.demo import Demo
from simulation.pick_place.kinematics import wrist_frame
from simulation.pick_place.scene import Scene

FINGERS = ("thumb", "index", "middle", "ring", "pinky")
KINDS = (("can", "upright"), ("can", "lying"), ("apple", "upright"), ("orange", "upright"), ("peach", "upright"))
# Right side of the bin-conveyor table, off the belt strip and clear of the box: the
# region the table objects are placed in (plan-checked spots (0.25,-0.28), (0.24,-0.39),
# (0.20,-0.37) all lie inside it).
X_RANGE = (0.22, 0.29)  # nearer x put the fruit's footprint off the work platform
Y_RANGE = (-0.42, -0.29)
RECORD_PERIOD_S = 0.1
RECORDED_PHASES = {"reach": 0, "grasp": 1}


def pose4(position: np.ndarray, rotation: np.ndarray) -> np.ndarray:
    out = np.eye(4)
    out[:3, :3], out[:3, 3] = rotation, position
    return out


def sample_setup(rng: np.random.Generator) -> tuple[str, str, tuple[float, float], float]:
    kind, rest = KINDS[int(rng.integers(len(KINDS)))]
    xy = (float(rng.uniform(*X_RANGE)), float(rng.uniform(*Y_RANGE)))
    yaw = float(rng.uniform(-180.0, 180.0))
    return kind, rest, xy, yaw


def make_scene(kind: str, rest: str, xy, yaw: float) -> Scene:
    return Scene(tuple(xy), BOX, work_platform_height=PLATFORM, pick_object=kind, pick_pose=rest, pick_yaw_deg=yaw,
                 basket_half_size=BOX_HALF, basket_wall_height=BOX_WALL, conveyor=BELT)


def run_episode(rng: np.random.Generator) -> tuple[dict | None, str]:
    kind, rest, xy, yaw = sample_setup(rng)
    try:
        scene = make_scene(kind, rest, xy, yaw)
    except ValueError as error:  # a spot the scene builder rejects (off the platform, overlap)
        return None, f"{kind}/{rest} at {np.round(xy, 3).tolist()}: {error}"
    demo = Demo(scene=scene, side="right", pose_backend="gt", release="drop", place_offset=(0.0, -0.10))
    demo.grasp_retries = 0  # a clean demonstration or none
    model, data = scene.model, scene.data
    side = "right"
    rows: dict[str, list] = {k: [] for k in ("time", "phase", "arm_q", "arm_ctrl", "hand_q", "hand_ctrl", "forces",
                                            "wrist", "wrist_cmd", "object", "object_est")}
    last = [-1.0]

    def record(executor) -> None:
        phase = demo.log.current_phase
        t = float(data.time)
        if phase not in RECORDED_PHASES or t - last[0] < RECORD_PERIOD_S - 1e-9:
            return
        last[0] = t
        arm_ctrl = data.ctrl[scene.arm_actuators[side]].copy()
        forces = scene.finger_contact_forces(side)
        rows["time"].append(t)
        rows["phase"].append(RECORDED_PHASES[phase])
        rows["arm_q"].append(data.qpos[scene.arm_qpos[side]].copy())
        rows["arm_ctrl"].append(arm_ctrl)
        rows["hand_q"].append(data.qpos[scene.hand_qpos[side]].copy())
        rows["hand_ctrl"].append(data.ctrl[scene.hand_actuators[side]].copy())
        rows["forces"].append(np.array([forces.get(f, 0.0) for f in FINGERS]))
        rows["wrist"].append(pose4(scene.wrist_position(side), scene.wrist_rotation(side)))
        rows["wrist_cmd"].append(pose4(*wrist_frame(model, side, arm_ctrl)))
        rows["object"].append(scene.object_pose())
        rows["object_est"].append(demo.perceived_pose.copy() if demo.perceived_pose is not None else scene.object_pose())

    demo.executor.on_step = record
    start_z = float(scene.object_position()[2])
    try:
        demo.run(stop_after="grasp")
    except RuntimeError as error:
        return None, f"{kind}/{rest} at {np.round(xy, 3).tolist()} yaw {yaw:+.0f}: {str(error).splitlines()[0][:120]}"
    rise = float(scene.object_position()[2]) - start_z
    if rise < 0.03 or len(rows["time"]) < 10:
        return None, f"{kind}/{rest}: object rose only {rise * 100:.1f} cm"
    episode = {k: np.asarray(v) for k, v in rows.items()}
    episode.update(kind=np.asarray(kind), pose=np.asarray(rest), xy=np.asarray(xy), yaw=np.asarray(yaw),
                   grasp_name=np.asarray(str(demo.log.values.get("grasp_name", ""))))
    return episode, f"{kind}/{rest} at {np.round(xy, 3).tolist()} yaw {yaw:+.0f}: ok, {len(rows['time'])} steps, rise {rise * 100:.1f} cm"


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Scripted grasp demonstrations for policy learning")
    parser.add_argument("--count", type=int, default=200, help="episodes to attempt")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--out", type=Path, default=Path("artifacts") / "demos")
    args = parser.parse_args(argv)
    args.out.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(args.seed)
    kept = 0
    for index in range(args.count):
        started = time.perf_counter()
        episode, message = run_episode(rng)
        if episode is not None:
            np.savez_compressed(args.out / f"s{args.seed:02d}_e{index:04d}.npz", **episode)
            kept += 1
        print(f"[seed {args.seed} #{index:4d}] {'KEEP' if episode is not None else 'drop'} {message} "
              f"({time.perf_counter() - started:.0f}s wall; kept {kept}/{index + 1})", flush=True)


if __name__ == "__main__":
    main()
